# Generated by Django 2.2 on 2019-06-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_man', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='confirm',
            new_name='confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
